var lista = {todos: ['luis.cortes@gojump.cl',
'lulacortes@hotmail.com'
,'moredls@yahoo.com.ar'
,'karen.sainz@nielsen.cl'
,'vivicarrasco@hotmail.com'
,'mauricio.zarate@primeintegral.com'
,'efernadezweber@hotmail.com'
,'barahonam@gmail.com'
,'clauparrag@hotmail.com'
,'carlos.madrid@gmail.com'
,'macarenakanacri@gmail.com'
,'laura.translations@gmail.com'
,'Andreas.Heuschkel@hlag.com'
,'lilita.saavedra@gmail.com'
,'katrippley@hotmail.com'
,'alva.rios@hotmail.com'
,'escalonaveloso@gmail.com'
,'pashcroft@me.com'
,'jose.bahamonde@gmail.com'
,'karen_rubino@hotmail.com'
,'valenfio@gmail.com'
,'Ktyfloresa@gmail.com'
,'sarinaperez@hotmail.com'
,'paula.zamorano.b@gmail.com'
,'cpogchile@gmail.com'
,'juanaravenaluna@hotmail.com'
,'emcmedanic@hotmail.com'
,'marlenpalma@hotmail.com'
,'sandralisperguer@vtr.net'
,'jac.araya@gmail.com'
,'paula@solari.cl'
,'dr.gmontenegro@gmail.com'
,'paulinabarckhahn@gmail.com'
,'natacaceresl@gmail.com'
,'caguerrero2@gmail.com'
,'andreaojeda@msn.com'
,'giustoandrea2@gmail.com'
,'veronica.escobar.gonzalez1974@gmail.com'
,'micamposarq@gmail.com'
,'carla.palominos83@gmail.com'
,'tamaraaguilera112@gmail.com'
,'michel.cure@uv.cl'
,'yael.araneda@gmail.com'
,'dracepeda@gmail.com'
,'manewos512@gmail.com'
,'carteravan@hotmail.com'
,'danielitacortes@gmail.com'
,'djohns@vtr.net'
,'v.a.d.m@hotmail.com'
,'abenaventee@gmail.com'
,'mabel.v@toquenativo.cl'
,'claudia.vicencio.v@gmail.com'
,'katherinejimenezcastillo83@gmail.com'
,'jmmontecinos@vtr.net'
,'alexis.moya@gmail.com'
,'balvarezvillarroel@gmail.com'
,'monyvelasquez@hotmail.com'
,'carlacespedespgmail.com'
,'solanshe.a@gmail.com'
,'mabel.v@toquenativo.cl'
,'ldiez@codelco.cl'
,'echaquu@yahoo.com'
,'mariafernandanunez@hotmail.com'
,'carmenpazca@hotmail.com'
,'fermaldonado@gmail.com'
,'solange.ht@gmail.com'
,'paulita.ib@gmail.com'
,'pcarcey@globalreefers.cl'
,'camilo.mori@uv.cl'
,'jcflores@minpublico.cl'
,'jeannette.a@hotmail.com'
,'kati.spichiger@gmail.com'
,'valeria.vasquez1981@gmail.com'
,'leticiallv@hotmail.com'
,'cynthia.kine.uv@gmail.com'
,'jvillanum@gmail.com'
,'ojeclau5@yahoo.es'
,'chewstoneg@intermodal.cl'
,'silvia.lopezm@redsalud.gov.cl'
,'francisca.jana@gmail.com'
,'cgorichon@reno.cl'
,'nataliavarasrojas@gmail.com'
,'evelynhernlab@hotmail.com'
,'cellacarras@mac.com'
,'amerinob2009@gmail.com'
,'camduva@gmail.com'
,'piafernanda.gn@gmail.com'
,'alefi2010@gmail.com'
,'jnashpj@yahoo.es'
,'pauvera@hotmail.com'
,'celestemolina10@hotmail.com'
,'FRABEAPA@GMAIL.COM'
,'juan.barrera@gmail.com'
,'geomensor.jorge@gmail.com'
,'vicentico712@gmail.com'
,'terezaes@gmail.com'
,'alejandraolivares@gmail.com'
,'ckrisol@yahoo.es'
,'asaldanac@vtr.net'
,'jucacabar@hotmail.com'
,'CAANJARIZ@GMAIL.COM'
,'Marcelaandrearodriguezsolis@gmail.com'
,'manuelgutierrezmar@gmail.com'
,'ivanesca76@gmail.com'
,'mabel.gallegos.c@hotmail.com'
,'CARLOSANDRESCN89@GMAIL.COM'
,'susangarces@hotmail.com'
,'nannypaz@gmail.com'
,'sofia.salustiano@gmail.com'
,'carolaeta@hotmail.com'
,'carolaibanezh@gmail.com'
,'c.morelrocca@gmail.com'
,'caturrock100@hotmail.com'
,'prodriguez@propal.cl'
,'fabiola.cabrera.v@gmail.com'
,'carlosandrescn89@gmail.com'
,'evelin.v123@gmail.com'
,'pao.calderog@gmail.com'
,'imateluna@colegiosscc.cl'
,'carolina.pulgar.silva@gmail.com'
,'guadalupeortiz72@hotmail.com'
,'eaguirreh@gmail.com'
,'anita.isabel.perez@gmail.com'
,'coloresdemitierra@gmail.com'
,'marpacita@gmail.com'
,'Denysv@vtr.net'
,'GONZALOALCALDE@ASGPRODUCCIONES.CL'
,'pamelavenegasp@gmail.com'
,'paulinaespinaza@gmail.com'
,'valeria.alvarez@santander.cl'
,'camilabarrerab@gmail.com'
,'vvonjohnn@gmail.com'
,'joannalozier@gmail.com'
,'jorge.avegno@gmail.com'
,'oscar.amv@gmail.com'
,'kschiappacasseg@gmail.com'
,'ahumada.galinou@gmail.com'
,'mlucero@bciseguros.cl'
,'tatianatorov@hotmail.com'
,'marcianavarromunoz@gmail.com'
,'mooreneb@gmail.com'
,'j.marin@vtr.net'
,'maryestrella14@hotmail.com'
,'r.vento.u@gmail.com'
,'crojas@puertovalparaiso.cl'
,'d.morales.sm@gmail.com'
,'igajardo@zeal.cl'
,'igajardo@zeal.cl'
,'kake.millones1413@gmail.com'
,'pattyolmos@hotmail.com'
,'katty.suarez@aol.com'
,'paolajara2102@gmail.com'
,'solekaczo@yahoo.es'
,'pjeldes@gmail.com'
,'nicolasaguilera71@gmail.com'
,'verosaez@yahoo.com'
,'mcardenasclaros@gmail.com'
,'balvarezvillarroel@gmail.com'
,'diegobadiab@hotmail.com'
,'patopuebla@yahoo.com'
,'monica.leonbecerra@gmail.com'
,'mpaz.abogada@gmail.com'
,'n_jaque@hotmail.com'
,'vega.oscarignacion@gmail.com'
,'gabrielahg@yahoo.es'
,'Macarenavalenzuelac@hotmail.com'
,'stgocatalan@mucky.cl'
,'rossanafloresp66@gmail.com'
,'selenmp@gmail.com'
,'siomara_sassi@bat.com'
,'maite.quiros@gmail.com'
,'marcelo.ma.silva@gmail.com'
,'valeria_a_o@hotmail.cl'
,'corita.candial@gmail.com'
,'galiasaenz@gmail.com'
,'jimolinaponce@gmail.com'
,'pgonzco@bci.cl'
,'ingridfernandez2008@yahoo.es'
,'paolarojassanchez@yahoo.com'
,'saraytv@gmail.com'
,'osvaldo.escarate@tekma.cl'
,'ventas@vgpavimentos.com'
,'carolinasaavedrag@gmail.com'
,'yamis.breff5@gmail.com'
,'danett.alvarez@gmail.com'
,'sandranotariajordan@gmail.com'
,'maaravenagatica@gmail.com'
,'haadesign@gmail.com'
,'maca.alastuey@gmail.com'
,'roxanavani08@hotmail.com'
,'pcantallopts@yahoo.es'
,'imirandap@gmail.com'
,'cafaundes@gmail.com'
,'stevensoncl@yahoo.com'
,'aquirozmoreira@icloud.com'
,'a.rodriguez.boye@gmail.com'
,'anlodilla@gmail.com'
,'carolina.ripamonti@gmail.com'
,'pjcisternab@gmail.com'
,'gabrielahg@yahoo.es'
,'mauracarolinav@gmail.com'
,'luis.e.yañez@gmail.com'
,'alejandro.zamora@upla.cl'
,'pereira.gonzalo.p@gmail.com'
,'xime.ovando.g@gmail.com'
,'egrr@bancoestado.cl'
,'CLAMARUIJO@GMAIL.COM'
,'sugarte@colegioaconcagua.cl'
,'joana.veliz.m@gmail.com'
,'antoollinoo@gmail.com'
,'solelozamo3@gmail.com'
,'dpacheh@hotmail.com'
,'henrryarriagada@hotmail.com'
,'mattar@vtr.net'
,'barrios.lizardi@gmail.com'
,'iriscprado@yahoo.com'
,'clamedina@deloitte.com'
,'catalagosb@hotmail.com'
,'solvargas@live.cl'
,'ppanes@gmail.com'
,'cony_rjs@htmail.com'
,'prodriguez@propal.cl'
,'oriettalarenas0@gmail.com'
,'vgcor@yahoo.es'
,'ialdaysepulveda@gmail.com'
,'falexandra.dlc@hotmail.com'
,'carlos.lara@uv.cl'
,'aimeetortorap@gmail.com'
,'rosa.gallardo@mop.gub.cl'
,'patopuebla@yahoo.com'
,'rosa.loyola@gmail.com'
,'jalman.lo@gmail.com'
,'alerodrguez_90@hotmail.com'
,'paocf@yahoo.com'
,'vinyaschi@yahoo.com'
,'antoromanini@outlook.com'
,'selenmp@gmail.com'
,'marjoriecastillo13@gmailcom'
,'digna.azua@pucv.cl'
,'mucaberrios@hotmail.com'
,'marcelo.jaure@gmail.com'
,'pcisternas23@yahoo.com'
,'mianvies@gmail.com'
,'tecvalpo@gmail.com'
,'qfclaudiagrrd@gmail.com'
,'pmauch@vtr.net'
,'dsanhueza.pucv@gmail.com'
,'cortes@gmail.com'
,'jeniiealejandra@hotmail.com'
,'a_prado79@hotmail.com'
,'c.aravena.bascur@gmail.com'
,'Givannadiaz9@gmail.com'
,'valeria.alvarez@santander.cl'
,'franderem@gmail.com'
,'fduveheise@gmail.com'
,'snavarrete17@gmail.com'
,'brendavalencia@gmail.com'
,'jafo.35@gmail.com'
,'yesselyn.mascareno@gmail.com'
,'stapiao@gmail.com'
,'rradebac@yahoo.com'
,'eugeniolizama@hotmail.com'
,'purabi.dasgupta@gmail.com'
,'cjba@vtr.net'
,'mpazalvear@gmail.com'
,'rodolfoencinas@hotmail.com'
,'paumardbarr@gmail.com'
,'libsanfranciscolimache@hotmail.com'
,'tacb2025@gmail.com'
,'vaccarezza.flavia@gmail.com'
,'svasquezs@saam.cl'
,'jorgedeantasl@hotmail.com'
,'patriciatoroa@hotmail.com'
,'paulina.fuenzalida@gmail.com'
,'cchavez@mackay.cl'
,'cminettio@gmail.com'
,'gabili.9@gmail.com'
,'lecrovetto.g@gmail.com'
,'silvia.g75@gmail.com'
,'javivaledober@gmail.com'
,'sandra.araya1@gmail.com'
,'saramcamus@gmail.com'
,'susana@smartharvest.cl'
,'maricelaurtubiac@hotmail.com'
,'andres_villagran@hotnail.com'
,'rodrigo.caceres@it-factory.cl'
,'marco.vera.castillo@gmail.com'
,'carolina.lopez.bravo@gmail.com'
,'acsepulveda@aduana.cl'
,'paumardbarr@gmail.com'
,'claudia.guarda.munoz@gmail.com'
,'alexiaraya@gmail.com'
,'angela.trevia@gmail.com'
,'patricialepe@gmail.com'
,'jdiazcarvajal2@hotmail.com'
,'angali@vtr.net'],
abmayo: [
'luis.cortes@gojump.cl',
'benjamin.meneses.14@sansano.usm.cl',
'm.compagna@gmail.com',
'h3aray@gmail.com',
'susan_ramirez@hotmail.com',
'susan_ramirezs@hotmail.com',
'ropupkin@gmail.com',
'jaa@123.cl',
'manava1975@gmail.com',
'mgreauk@hotmail.com',
'ximenaponce028@gmail.com',
'sebastiansotog@gmail.com',
'pbrockmann@gmail.com',
'alanfernandezgonzalez@gmail.com',
'andreaastudillorojas@gmail.com',
'N_NOVOA@HOTMAIL.COM',
'tammy773@hotmail.com',
'isabelmaciasaraya@gmail.com',
'pseverin@gmaill.com',
'andres@citrica.cl',
'claudioguzmanolea@gmail.com',
'angelavasqueze@gmail.com',
'mauromunoz6@gmail.com',
'PJCONTRERAS@GMAIL.COM',
'gajeria@gmail.com',
'pbrecci@gmail.com',
'marcela.bonilla.oryan@gmail.com',
'marielymr@gmail.com',
'luisale2@gmail.com',
'andrea.cook.h@gmail.com',
'renemogollon@gmail.com',
'sofi_delotero@hotmail.com',
'cgalvezm@vtr.net',
'felipehd316@gmail.com',
'soleavilesv@gmail.com',
'carvallal10@gamil.com',
'Cali.prat@gmail.com',
'pc.cristian25@hotmail.com',
'VIAALBENJAMIN@GMAIL.COM',
'victoria.perez.smith@hotmail.cl',
'sebastiantorres.donoso@gmail.com',
'josemanuel.ad@hotmail.com',
'ingrid.hernandez.fernandez@gmail.com',
'alfr.zunigaibarra@gmail.com',
'fonfachh@gmail.com',
'floresdanielar@gmail.com',
'daniela.petersen.droguett@gmail.com',
'f.araya@live.cl',
'adrianjofrearaya@gmail.com',
'mariaeugeniadiaz1714@gmail.com',
'danieldelpozos@gmail.com',
'sabores.mayorga@gmail.com',
'valeria_iturra@hotmail.com',
'es.loyola63@gmail.com',
'marcoa.munozn@gmail.com',
'ccc.isla@gmail.com',
'rballimants@gmail.com',
'jose@gmail.com',
'kaarem@hotmail.es',
'andreacorvaz@yahoo.com',
'benjakraus@gmail.com',
'rtolozaguardia@gmail.com',
'valentina.bravo.v@gmail.com',
'claudio.aen@live.cl',
'camolinarim@gmail.com',
'VOLCAJOHAN@GMAIL.COM',
'liph3_sk8@hotmail.com',
'agustinguerrero1711@gmail.com',
'ANGELYDUGARTEVALERA@GMAIL.COM',
'nicolas_bz@hotmail.com',
'camila.martinez@culinary.cl',
'tomasgonzalezt@hotmail.com',
'emunyozb@gmail.com',
'katherinet99@gmail.com',
'pedropquezadav@gmail.com',
'JUANPABLODIAZARANCIBIA99@GMAIL.COM',
'CATA.SCHNEIDE02@GMAIL.COM',
'marialy08@hotmail.com',
'gmariangelr@hotmail.com',
'juliettemadeline@gmail.com',
'zuletacalvetti@gmail.com',
'bastian_amaya@hotmail.com',
'L_CERDA20@HOTMAIL.COM',
'jorgecampscarreno@hotmail.com',
'lolmos.72@hotmail.com',
'iramirez_martinez@yahoo.com',
'jesulohmane@gmail.com',
'sonlla77@gmail.com',
'cbrigna@gmail.com',
'poly_rojas@yahoo.es',
'malejandrabadilla@gmail.com',
'ILABACAROBLES@HOTMAIL.COM',
'carlalavarellob@gmail.com',
'ksprasse@uc.cl',
'andrearc07@hotmail.com',
'jicardenas@cygabogados.cl',
'loreto_paredes@yahoo.com',
'kattycornejo@gmail.com',
'angelica150507@gmail.com',
'dario99dj.js@hotmail.com',
'any21cl@hotmail.com',
'leonoraluzmartinez@hotmail.com',
'soledad.trejo.rojas@gmail.com',
'pablovalenzuela@icloud.com',
'alita.altla@gmail.com',
'isabelperezluci@gmail.com',
'javicedo@gmail.com',
'ctudela2002@yahoo.es',
'voces@lives.cl',
'quenososaleiva@gmail.com',
'vi.paz@live.com',
'axelc1@hotmail.com',
'lydaprada@hotmail.com',
'juliort.benavente@gmail.com',
'claudiaalejandrahb@hotmail.com',
'ariel_diaz@live.cl',
'maor@lwow.es',
'tahiarozas@yahoo.com',
'beltran_gustavo@yahoo.com',
'daniela.ramos@alumnos.uv.cl',
'skmr_23@yahoo.com',
'jmaldonado1901@gmail.com',
'brahmer@uc.cl',
'karinamena30@gmail.com',
'director.marcelo@gmail.com',
'arturoparrac@gmail.com',
'patricia.gomez.cappelli@gmail.com',
'caroromero.rivas@gmail.com',
'marcella.sanchez@gmail.com',
'MCARMONP@UC.CL',
'mariajosecortines@gmail.com',
'shaendmig2010@hotmail.com',
'arayagiuliani18@gmail.com',
'paulistel@gmail.com',
'carlotafritsch@vtr.net',
'dgarcialobos@gmail.com',
'Paulinamaureira72@gmai.com',
'pleonstehr@gmail.com',
'leyterc@gmail.com',
'muriybenji2207@gmail.com',
'cgaldamg05@gmail.com',
'daniela.isalazar@gmail.com',
'pazgarrido.becerra@gmail.com',
'yolalvargas@hotmail.com',
'kikagarces@hotmail.com',
'anitapinilla@gmail.com',
'barbara.m.w@gmail.com',
'plmartin@uc.cl',
'molina.daniela@gmail.com',
'RODRIGO8828@GMAIL.COM',
'mvarasl@vtr.net',
'babmonje@gmail.com',
'oyarzoquijada@gmail.com',
'hersin@hotmail.com',
'vmadrid.soto@gmail.com',
'cesar.alvarez.vasquez@gmail.com',
'aguerovictor@hotmail.com',
'10.amos@gmail.ccom',
'polabarriga@gmail.com',
'pzaratep@gmail.com',
'yee_yee_y@hotmail.com',
'hadde.valencia93@gmail.com',
'dalvarez@uc.cl',
'mmontoyal@me.com',
'luishellen3936@gmail.com',
'barbara.kilian.castro@gmail.com',
'jaquelinevidela@yahoo.com',
'maryrubiorojas@gmail.com',
'alejandravita.l@gmail.com',
'claracarvega@gmail.com',
'gellerdafna@gmail.com',
'aleha38@hotmail.com',
'cquintap@uc.cl',
'claudiafa76@gmail.com',
'java.jav@gmail.com',
'juan.calcacheb@gmail.com',
'JBSHAE@GMAIL.COM',
'juan.antriao@saesa.cl',
'DDIAZ_CL@VTR.NET',
'marceladuranduran@gmail.com',
'carolina.stubing19@gmail.com',
'jardinescampomanes@gmail.com',
'petit.nelly@gmail.com',
'EV@ELVIRAVALENZUELA.CL',
'gnicole.andrea@gmail.com',
'andreslunab@hotmail.com',
'cevicuna@gmail.com',
'alejandroperezpeters@gmail.com',
'mario.guiloff@gmail.com',
'ARRAUS.MJ@GMAIL.COM',
'claudio.ferrada@live.com',
'ING.FELIPE.GUERRERO@GMAIL.COM',
'valentina.abalo@gmail.com',
'eliette.herradura@yahoo.es',
'PHARTUNGM@GMAIL.COM',
'veronicagatica@gmail.com',
'promanr@gmail.com',
'karroninus@gmail.com',
'j.vicencio@colver.cl',
'aleschain@hotmail.com',
'gracielasn@hotmail.com',
'MARTINPERO2003@GMAIL.COM',
'marcos.valenzuela@gmail.com',
'alejgodoy@yahoo.es',
'pzuniga@vespucionorte.cl',
'silvanapavez.pena@gmail.com',
'educadora.karentorres@gmail.com',
'cecivgt@gmail.com',
'juaneduardo.pizarro@eqifax.cl',
'lbarreram@gmail.com',
'carlos-melo-s@hotmail.com',
'mchv.1980@gmail.com',
'pamelajeriapeperic@gmail.com',
'marielbeker@gmail.com',
'pfarfan@verbar.cl',
'MARICARMEN0409@GMAIL.COM',
'MALUCHICHA@GMAIL.COM',
'rjlfsimons@gmail.com',
'BLAMBERGARI@GMAIL.COM',
'ramonbenitezaranguiz@hotmail.com',
'lfwuth@hotmail.com',
'afuenzalida.palma@gmail.com',
'MPAZARAB@GMAIL.COM',
'aletetuppe@gmail.com',
'cristian.arcos@chilevision.cl',
'fcomarciel@live.com',
'mariajose_cote21@hotmail.com',
'grabriellajaraa@gmail.com',
'leonardokine16@gmail.com',
'ugonzalezc@gmail.com',
'lia_76@live.cl',
'sbellocchio@gmail.com',
'petersen.segsue@gmail.com',
'caravenaduran@gmail.com',
'caroleiva20@hotmail.com',
'salinasbustamante.camila@gmail.com',
'rwurgaft@gmail.com',
'paz.astudillo@gmail.com',
'franjomi.gas21@gmail.com',
'carolrabiech@gmail.com',
'xaltuzarra@gmail.com',
'tomarielag@gmail.com',
'ximarni@hotmail.com',
'mariola.saldarriaga@gmail.com',
'cataran@hotmail.com',
'anacona.carolina@gmail.com',
'vlarrondo@gmail.com',
'JCRQ77@GMAIL.COM',
'correo.cristian@gmail.com',
'isabelscheuch@gmail.com',
's.santibanez508@gmail.com',
'sebastian.hernandez.avendano@gmail.com',
'MAYERLIN_CARRUYO@HOTMAIL.COM',
'danielabelmart@gmaill.com',
'negal.rivero@gmail.com',
'carolina@consultorapanal.com',
'ravelis@gmail.com',
'MSERRAZURIZ@GMAIL.COM',
'jorgedp72@hotmail.com',
'dalibormilkovic@gmail.com',
'fdavila@banmedica.cl',
'hcalderovtr@gmail.com',
'jmbmd33@gmail.com',
'metulain@dicenciasonline.com',
'jaelalvo@gmail.com',
'gonzalo.aguilar.d@gmail.com',
'silvana.caroca@gmaIL.com',
'daniel.endi@gmail.com',
'jaime_rivera_md@yahoo.es',
'carlamnouel@hotmail.com',
'carocevallosbarrera@hotmail.com',
'danielruz.galvez@gmail.com',
'inunez_13@hotmail.com',
'mbenavente@arbolcolor.cl',
'alvarezlobofran@gmail.com',
'candypatino25@hotmail.com',
'claumeramunoz@gmail.com',
'ana.brandt@gmail.com',
'andyter@yahoo.com',
'olirav@aol.com',
'marchant.mariana@gmail.com',
'cgotelliw@gmail.com',
'dfoncea@gmail.com',
'paulacorreal@yahoo.es',
'defnny@gmail.com',
'ALAGOSVARELA@GMAIL.COM',
'carito7510@gmail.com',
'cpaz.peralta@gmail.com',
'cecilianbi@yahoo.com',
'francobasualto@gmail.com',
'edgalopez@gmail.com',
'imelnick@aol.com',
'raqel1703@gmail.com',
'vhutter@hofmann.cl',
'viviana.bugueno@gmail.com',
'tatacruci14@gmail.com',
'camila.jorquera.o@gmail.com',
'CECILIABEZ@HOTMAIL.COM',
'tamita2_87@hotmail.com',
'spavezl@gmail.com',
'papiruza2@gmail.com',
'camilavernal@gmail.com',
'josmig888@gmail.com',
'dacampos@puc.cl',
'maricelcm@gmail.com',
'lodasid@gmail.com',
'daguileram.qf@gmail.com',
'vespinosa@kikirikits.cl',
'nancy.pardo@live.cl',
'mjdurang@gmail.com',
'paduni@gmail.com',
'JOEGEYANKOVIC@GMAIL.COM',
'pablovn@gmail.com',
'tomaedo@gmail.com',
'caroguerracarrasco@gmail.com',
'eitan@fardo.cl',
'fco.jose.f@gmail.com',
'jpsanchezgarcia@gmail.com',
'alexrenevegaolivares@gmail.com',
'cata.poblete.ll@gmail.com',
'MPCASTILSTER@GMAIL.COM',
'fernanda.cabadillas@santander.cl',
'cosntazabarrosoj@gmail.com',
'stephaniechavarriatoro@gmail.com',
'coteblanco89@hotmail.com',
'eduardoj@me.com',
'javiera.fisher@gmail.com',
'pietrotauria17@gmail.com',
'aydembalajes@gmail.com',
'Neliaflores@hotmail.es',
'pazbarboza@hotmail.com',
'ka.saez@gmail.com',
'mjosevasquez@gmail.com',
'lidiamont@yahoo.cl',
'andreacarolina.mp@gmail.com',
'zacariasclaudia@gmail.com',
'danyespy2@gmail.com',
'camilacisternasz@gmail.com',
'cponcecaballero@gmail.com',
'pas7979@hotmail.com',
'dnavarro.toro@gmail.com',
'arturgarcia@outcklo.com',
'jvidall@dartel.cl',
'jcarcaval@hotmail.com',
'mjriquelme@gmail.com',
'yuyi@live.cl',
'IVETTE.VALDERRAMA.C@GMAIL.COM',
'aarayagu@uce.cl',
'MARIA.AUAD@MI.CL',
'MCASSISM@HOTMAIL.COM',
'hernandez.chr@gmail.com',
'teckaeltzerf@gmail.com',
'maopazo@gmail.com',
'fjdelpozo@gmail.com',
'luis_coa83@yahoo.com',
'rodrigosilva73@gmail.com',
'MARIPAULEK@HOTMAIL.COM',
'mtsilvav@gmail.com',
'margarita.alvares.l@gmail.com',
'trmatiasponce@gmail.com',
'claudiapoggio84@gmail.com',
'mabaud@gmail.com',
'alison.serrano@gmail.com',
'LIZZIEKABALAN@GMAIL.COM',
'aretuet@gmail.com',
'alfredo@skmedical.cl',
'mjcasals@gmail.com',
'ceciliatrigodaroni@gmail.cojm',
'christian.guerrag@gmail.com',
'rodrigo.carroza@gmail.com',
'manuel.reyes84@gmail.com',
'patybottai@gmail.com',
'DANIELAACEITUNO@HOTMAIL.COM',
'allvaro_0910@hotmail.com',
'monicagarciat@gmail.com',
'garansibiaf@me.com',
'gino.suppa@gmail.com',
'lorenavillarroelg@gmail.com',
'alberto.arayarojas@gmail.com',
'danielmoralesbrucher@gmail.com',
'caro.lasala@gmail.com',
'solherre@gmail.com',
'familiaviearevalo@gmail.com',
'fer.chica@gmaill.com',
'romaya1977@hotmail.com',
'diegozunigaacosta@gmail.com',
'mauro.bkp@gmail.com',
'daniza.faundez@gmail.com',
'daniel@invermaster.cl',
'ni.ibanez92@gmail.com',
'esteban.fuentes.morales@gmail.com',
'jbaraonau@gmail.com',
'julio@creastudio.cl',
'VERONICA.DAVANZO@GMAIL.COM',
'j.genacio.bravo@gmail.com',
'akikomc@gmail.com',
'mvelazquez07@gmail.com',
'YUVITZA.MUNOZ@GMAIL.COM',
'nicovicuna@gmail.com',
'fernanda.asp@gmail.com',
'ANAVILLABLANCA@HOTMAIL.COM',
'bsanchezblank@hotmal.com',
'felipefernandez79@gmail.com',
'soymontana@hotmail.com',
'ines.romero1@gmail.com',
'fram.marambio29@gmail.com',
'leonsacks84@gmail.com',
'pamevargas@hotmail.com',
'apuzito@gmail.com']};

module.exports = lista;