var lista = {
    todos: ['luis.cortes@gojump.cl',
'lulacortes@hotmail.com'
,'moredls@yahoo.com.ar'
,'karen.sainz@nielsen.cl'
,'vivicarrasco@hotmail.com'
,'mauricio.zarate@primeintegral.com'
,'efernadezweber@hotmail.com'
,'barahonam@gmail.com'
,'clauparrag@hotmail.com'
,'carlos.madrid@gmail.com'
,'macarenakanacri@gmail.com'
,'laura.translations@gmail.com'
,'Andreas.Heuschkel@hlag.com'
,'lilita.saavedra@gmail.com'
,'katrippley@hotmail.com'
,'alva.rios@hotmail.com'
,'escalonaveloso@gmail.com'
,'pashcroft@me.com'
,'jose.bahamonde@gmail.com'
,'karen_rubino@hotmail.com'
,'valenfio@gmail.com'
,'Ktyfloresa@gmail.com'
,'sarinaperez@hotmail.com'
,'paula.zamorano.b@gmail.com'
,'cpogchile@gmail.com'
,'juanaravenaluna@hotmail.com'
,'emcmedanic@hotmail.com'
,'marlenpalma@hotmail.com'
,'sandralisperguer@vtr.net'
,'jac.araya@gmail.com'
,'paula@solari.cl'
,'dr.gmontenegro@gmail.com'
,'paulinabarckhahn@gmail.com'
,'natacaceresl@gmail.com'
,'caguerrero2@gmail.com'
,'andreaojeda@msn.com'
,'giustoandrea2@gmail.com'
,'veronica.escobar.gonzalez1974@gmail.com'
,'micamposarq@gmail.com'
,'carla.palominos83@gmail.com'
,'tamaraaguilera112@gmail.com'
,'michel.cure@uv.cl'
,'yael.araneda@gmail.com'
,'dracepeda@gmail.com'
,'manewos512@gmail.com'
,'carteravan@hotmail.com'
,'danielitacortes@gmail.com'
,'djohns@vtr.net'
,'v.a.d.m@hotmail.com'
,'abenaventee@gmail.com'
,'mabel.v@toquenativo.cl'
,'claudia.vicencio.v@gmail.com'
,'katherinejimenezcastillo83@gmail.com'
,'jmmontecinos@vtr.net'
,'alexis.moya@gmail.com'
,'balvarezvillarroel@gmail.com'
,'monyvelasquez@hotmail.com'
,'carlacespedespgmail.com'
,'solanshe.a@gmail.com'
,'mabel.v@toquenativo.cl'
,'ldiez@codelco.cl'
,'echaquu@yahoo.com'
,'mariafernandanunez@hotmail.com'
,'carmenpazca@hotmail.com'
,'fermaldonado@gmail.com'
,'solange.ht@gmail.com'
,'paulita.ib@gmail.com'
,'pcarcey@globalreefers.cl'
,'camilo.mori@uv.cl'
,'jcflores@minpublico.cl'
,'jeannette.a@hotmail.com'
,'kati.spichiger@gmail.com'
,'valeria.vasquez1981@gmail.com'
,'leticiallv@hotmail.com'
,'cynthia.kine.uv@gmail.com'
,'jvillanum@gmail.com'
,'ojeclau5@yahoo.es'
,'chewstoneg@intermodal.cl'
,'silvia.lopezm@redsalud.gov.cl'
,'francisca.jana@gmail.com'
,'cgorichon@reno.cl'
,'nataliavarasrojas@gmail.com'
,'evelynhernlab@hotmail.com'
,'cellacarras@mac.com'
,'amerinob2009@gmail.com'
,'camduva@gmail.com'
,'piafernanda.gn@gmail.com'
,'alefi2010@gmail.com'
,'jnashpj@yahoo.es'
,'pauvera@hotmail.com'
,'celestemolina10@hotmail.com'
,'FRABEAPA@GMAIL.COM'
,'juan.barrera@gmail.com'
,'geomensor.jorge@gmail.com'
,'vicentico712@gmail.com'
,'terezaes@gmail.com'
,'alejandraolivares@gmail.com'
,'ckrisol@yahoo.es'
,'asaldanac@vtr.net'
,'jucacabar@hotmail.com'
,'CAANJARIZ@GMAIL.COM'
,'Marcelaandrearodriguezsolis@gmail.com'
,'manuelgutierrezmar@gmail.com'
,'ivanesca76@gmail.com'
,'mabel.gallegos.c@hotmail.com'
,'CARLOSANDRESCN89@GMAIL.COM'
,'susangarces@hotmail.com'
,'nannypaz@gmail.com'
,'sofia.salustiano@gmail.com'
,'carolaeta@hotmail.com'
,'carolaibanezh@gmail.com'
,'c.morelrocca@gmail.com'
,'caturrock100@hotmail.com'
,'prodriguez@propal.cl'
,'fabiola.cabrera.v@gmail.com'
,'carlosandrescn89@gmail.com'
,'evelin.v123@gmail.com'
,'pao.calderog@gmail.com'
,'imateluna@colegiosscc.cl'
,'carolina.pulgar.silva@gmail.com'
,'guadalupeortiz72@hotmail.com'
,'eaguirreh@gmail.com'
,'anita.isabel.perez@gmail.com'
,'coloresdemitierra@gmail.com'
,'marpacita@gmail.com'
,'Denysv@vtr.net'
,'GONZALOALCALDE@ASGPRODUCCIONES.CL'
,'pamelavenegasp@gmail.com'
,'paulinaespinaza@gmail.com'
,'valeria.alvarez@santander.cl'
,'camilabarrerab@gmail.com'
,'vvonjohnn@gmail.com'
,'joannalozier@gmail.com'
,'jorge.avegno@gmail.com'
,'oscar.amv@gmail.com'
,'kschiappacasseg@gmail.com'
,'ahumada.galinou@gmail.com'
,'mlucero@bciseguros.cl'
,'tatianatorov@hotmail.com'
,'marcianavarromunoz@gmail.com'
,'mooreneb@gmail.com'
,'j.marin@vtr.net'
,'maryestrella14@hotmail.com'
,'r.vento.u@gmail.com'
,'crojas@puertovalparaiso.cl'
,'d.morales.sm@gmail.com'
,'igajardo@zeal.cl'
,'igajardo@zeal.cl'
,'kake.millones1413@gmail.com'
,'pattyolmos@hotmail.com'
,'katty.suarez@aol.com'
,'paolajara2102@gmail.com'
,'solekaczo@yahoo.es'
,'pjeldes@gmail.com'
,'nicolasaguilera71@gmail.com'
,'verosaez@yahoo.com'
,'mcardenasclaros@gmail.com'
,'balvarezvillarroel@gmail.com'
,'diegobadiab@hotmail.com'
,'patopuebla@yahoo.com'
,'monica.leonbecerra@gmail.com'
,'mpaz.abogada@gmail.com'
,'n_jaque@hotmail.com'
,'vega.oscarignacion@gmail.com'
,'gabrielahg@yahoo.es'
,'Macarenavalenzuelac@hotmail.com'
,'stgocatalan@mucky.cl'
,'rossanafloresp66@gmail.com'
,'selenmp@gmail.com'
,'siomara_sassi@bat.com'
,'maite.quiros@gmail.com'
,'marcelo.ma.silva@gmail.com'
,'valeria_a_o@hotmail.cl'
,'corita.candial@gmail.com'
,'galiasaenz@gmail.com'
,'jimolinaponce@gmail.com'
,'pgonzco@bci.cl'
,'ingridfernandez2008@yahoo.es'
,'paolarojassanchez@yahoo.com'
,'saraytv@gmail.com'
,'osvaldo.escarate@tekma.cl'
,'ventas@vgpavimentos.com'
,'carolinasaavedrag@gmail.com'
,'yamis.breff5@gmail.com'
,'danett.alvarez@gmail.com'
,'sandranotariajordan@gmail.com'
,'maaravenagatica@gmail.com'
,'haadesign@gmail.com'
,'maca.alastuey@gmail.com'
,'roxanavani08@hotmail.com'
,'pcantallopts@yahoo.es'
,'imirandap@gmail.com'
,'cafaundes@gmail.com'
,'stevensoncl@yahoo.com'
,'aquirozmoreira@icloud.com'
,'a.rodriguez.boye@gmail.com'
,'anlodilla@gmail.com'
,'carolina.ripamonti@gmail.com'
,'pjcisternab@gmail.com'
,'gabrielahg@yahoo.es'
,'mauracarolinav@gmail.com'
,'luis.e.yañez@gmail.com'
,'alejandro.zamora@upla.cl'
,'pereira.gonzalo.p@gmail.com'
,'xime.ovando.g@gmail.com'
,'egrr@bancoestado.cl'
,'CLAMARUIJO@GMAIL.COM'
,'sugarte@colegioaconcagua.cl'
,'joana.veliz.m@gmail.com'
,'antoollinoo@gmail.com'
,'solelozamo3@gmail.com'
,'dpacheh@hotmail.com'
,'henrryarriagada@hotmail.com'
,'mattar@vtr.net'
,'barrios.lizardi@gmail.com'
,'iriscprado@yahoo.com'
,'clamedina@deloitte.com'
,'catalagosb@hotmail.com'
,'solvargas@live.cl'
,'ppanes@gmail.com'
,'cony_rjs@htmail.com'
,'prodriguez@propal.cl'
,'oriettalarenas0@gmail.com'
,'vgcor@yahoo.es'
,'ialdaysepulveda@gmail.com'
,'falexandra.dlc@hotmail.com'
,'carlos.lara@uv.cl'
,'aimeetortorap@gmail.com'
,'rosa.gallardo@mop.gub.cl'
,'patopuebla@yahoo.com'
,'rosa.loyola@gmail.com'
,'jalman.lo@gmail.com'
,'alerodrguez_90@hotmail.com'
,'paocf@yahoo.com'
,'vinyaschi@yahoo.com'
,'antoromanini@outlook.com'
,'selenmp@gmail.com'
,'marjoriecastillo13@gmailcom'
,'digna.azua@pucv.cl'
,'mucaberrios@hotmail.com'
,'marcelo.jaure@gmail.com'
,'pcisternas23@yahoo.com'
,'mianvies@gmail.com'
,'tecvalpo@gmail.com'
,'qfclaudiagrrd@gmail.com'
,'pmauch@vtr.net'
,'dsanhueza.pucv@gmail.com'
,'cortes@gmail.com'
,'jeniiealejandra@hotmail.com'
,'a_prado79@hotmail.com'
,'c.aravena.bascur@gmail.com'
,'Givannadiaz9@gmail.com'
,'valeria.alvarez@santander.cl'
,'franderem@gmail.com'
,'fduveheise@gmail.com'
,'snavarrete17@gmail.com'
,'brendavalencia@gmail.com'
,'jafo.35@gmail.com'
,'yesselyn.mascareno@gmail.com'
,'stapiao@gmail.com'
,'rradebac@yahoo.com'
,'eugeniolizama@hotmail.com'
,'purabi.dasgupta@gmail.com'
,'cjba@vtr.net'
,'mpazalvear@gmail.com'
,'rodolfoencinas@hotmail.com'
,'paumardbarr@gmail.com'
,'libsanfranciscolimache@hotmail.com'
,'tacb2025@gmail.com'
,'vaccarezza.flavia@gmail.com'
,'svasquezs@saam.cl'
,'jorgedeantasl@hotmail.com'
,'patriciatoroa@hotmail.com'
,'paulina.fuenzalida@gmail.com'
,'cchavez@mackay.cl'
,'cminettio@gmail.com'
,'gabili.9@gmail.com'
,'lecrovetto.g@gmail.com'
,'silvia.g75@gmail.com'
,'javivaledober@gmail.com'
,'sandra.araya1@gmail.com'
,'saramcamus@gmail.com'
,'susana@smartharvest.cl'
,'maricelaurtubiac@hotmail.com'
,'andres_villagran@hotnail.com'
,'rodrigo.caceres@it-factory.cl'
,'marco.vera.castillo@gmail.com'
,'carolina.lopez.bravo@gmail.com'
,'acsepulveda@aduana.cl'
,'paumardbarr@gmail.com'
,'claudia.guarda.munoz@gmail.com'
,'alexiaraya@gmail.com'
,'angela.trevia@gmail.com'
,'patricialepe@gmail.com'
,'jdiazcarvajal2@hotmail.com'
,'angali@vtr.net'],
    abmayo: [
'luis.cortes@gojump.cl',
'benjamin.meneses.14@sansano.usm.cl',
'm.compagna@gmail.com',
'h3aray@gmail.com',
'susan_ramirez@hotmail.com',
'susan_ramirezs@hotmail.com',
'ropupkin@gmail.com',
'jaa@123.cl',
'manava1975@gmail.com',
'mgreauk@hotmail.com',
'ximenaponce028@gmail.com',
'sebastiansotog@gmail.com',
'pbrockmann@gmail.com',
'alanfernandezgonzalez@gmail.com',
'andreaastudillorojas@gmail.com',
'N_NOVOA@HOTMAIL.COM',
'tammy773@hotmail.com',
'isabelmaciasaraya@gmail.com',
'pseverin@gmaill.com',
'andres@citrica.cl',
'claudioguzmanolea@gmail.com',
'angelavasqueze@gmail.com',
'mauromunoz6@gmail.com',
'PJCONTRERAS@GMAIL.COM',
'gajeria@gmail.com',
'pbrecci@gmail.com',
'marcela.bonilla.oryan@gmail.com',
'marielymr@gmail.com',
'luisale2@gmail.com',
'andrea.cook.h@gmail.com',
'renemogollon@gmail.com',
'sofi_delotero@hotmail.com',
'cgalvezm@vtr.net',
'felipehd316@gmail.com',
'soleavilesv@gmail.com',
'carvallal10@gamil.com',
'Cali.prat@gmail.com',
'pc.cristian25@hotmail.com',
'VIAALBENJAMIN@GMAIL.COM',
'victoria.perez.smith@hotmail.cl',
'sebastiantorres.donoso@gmail.com',
'josemanuel.ad@hotmail.com',
'ingrid.hernandez.fernandez@gmail.com',
'alfr.zunigaibarra@gmail.com',
'fonfachh@gmail.com',
'floresdanielar@gmail.com',
'daniela.petersen.droguett@gmail.com',
'f.araya@live.cl',
'adrianjofrearaya@gmail.com',
'mariaeugeniadiaz1714@gmail.com',
'danieldelpozos@gmail.com',
'sabores.mayorga@gmail.com',
'valeria_iturra@hotmail.com',
'es.loyola63@gmail.com',
'marcoa.munozn@gmail.com',
'ccc.isla@gmail.com',
'rballimants@gmail.com',
'jose@gmail.com',
'kaarem@hotmail.es',
'andreacorvaz@yahoo.com',
'benjakraus@gmail.com',
'rtolozaguardia@gmail.com',
'valentina.bravo.v@gmail.com',
'claudio.aen@live.cl',
'camolinarim@gmail.com',
'VOLCAJOHAN@GMAIL.COM',
'liph3_sk8@hotmail.com',
'agustinguerrero1711@gmail.com',
'ANGELYDUGARTEVALERA@GMAIL.COM',
'nicolas_bz@hotmail.com',
'camila.martinez@culinary.cl',
'tomasgonzalezt@hotmail.com',
'emunyozb@gmail.com',
'katherinet99@gmail.com',
'pedropquezadav@gmail.com',
'JUANPABLODIAZARANCIBIA99@GMAIL.COM',
'CATA.SCHNEIDE02@GMAIL.COM',
'marialy08@hotmail.com',
'gmariangelr@hotmail.com',
'juliettemadeline@gmail.com',
'zuletacalvetti@gmail.com',
'bastian_amaya@hotmail.com',
'L_CERDA20@HOTMAIL.COM',
'jorgecampscarreno@hotmail.com',
'lolmos.72@hotmail.com',
'iramirez_martinez@yahoo.com',
'jesulohmane@gmail.com',
'sonlla77@gmail.com',
'cbrigna@gmail.com',
'poly_rojas@yahoo.es',
'malejandrabadilla@gmail.com',
'ILABACAROBLES@HOTMAIL.COM',
'carlalavarellob@gmail.com',
'ksprasse@uc.cl',
'andrearc07@hotmail.com',
'jicardenas@cygabogados.cl',
'loreto_paredes@yahoo.com',
'kattycornejo@gmail.com',
'angelica150507@gmail.com',
'dario99dj.js@hotmail.com',
'any21cl@hotmail.com',
'leonoraluzmartinez@hotmail.com',
'soledad.trejo.rojas@gmail.com',
'pablovalenzuela@icloud.com',
'alita.altla@gmail.com',
'isabelperezluci@gmail.com',
'javicedo@gmail.com',
'ctudela2002@yahoo.es',
'voces@lives.cl',
'quenososaleiva@gmail.com',
'vi.paz@live.com',
'axelc1@hotmail.com',
'lydaprada@hotmail.com',
'juliort.benavente@gmail.com',
'claudiaalejandrahb@hotmail.com',
'ariel_diaz@live.cl',
'maor@lwow.es',
'tahiarozas@yahoo.com',
'beltran_gustavo@yahoo.com',
'daniela.ramos@alumnos.uv.cl',
'skmr_23@yahoo.com',
'jmaldonado1901@gmail.com',
'brahmer@uc.cl',
'karinamena30@gmail.com',
'director.marcelo@gmail.com',
'arturoparrac@gmail.com',
'patricia.gomez.cappelli@gmail.com',
'caroromero.rivas@gmail.com',
'marcella.sanchez@gmail.com',
'MCARMONP@UC.CL',
'mariajosecortines@gmail.com',
'shaendmig2010@hotmail.com',
'arayagiuliani18@gmail.com',
'paulistel@gmail.com',
'carlotafritsch@vtr.net',
'dgarcialobos@gmail.com',
'Paulinamaureira72@gmai.com',
'pleonstehr@gmail.com',
'leyterc@gmail.com',
'muriybenji2207@gmail.com',
'cgaldamg05@gmail.com',
'daniela.isalazar@gmail.com',
'pazgarrido.becerra@gmail.com',
'yolalvargas@hotmail.com',
'kikagarces@hotmail.com',
'anitapinilla@gmail.com',
'barbara.m.w@gmail.com',
'plmartin@uc.cl',
'molina.daniela@gmail.com',
'RODRIGO8828@GMAIL.COM',
'mvarasl@vtr.net',
'babmonje@gmail.com',
'oyarzoquijada@gmail.com',
'hersin@hotmail.com',
'vmadrid.soto@gmail.com',
'cesar.alvarez.vasquez@gmail.com',
'aguerovictor@hotmail.com',
'10.amos@gmail.ccom',
'polabarriga@gmail.com',
'pzaratep@gmail.com',
'yee_yee_y@hotmail.com',
'hadde.valencia93@gmail.com',
'dalvarez@uc.cl',
'mmontoyal@me.com',
'luishellen3936@gmail.com',
'barbara.kilian.castro@gmail.com',
'jaquelinevidela@yahoo.com',
'maryrubiorojas@gmail.com',
'alejandravita.l@gmail.com',
'claracarvega@gmail.com',
'gellerdafna@gmail.com',
'aleha38@hotmail.com',
'cquintap@uc.cl',
'claudiafa76@gmail.com',
'java.jav@gmail.com',
'juan.calcacheb@gmail.com',
'JBSHAE@GMAIL.COM',
'juan.antriao@saesa.cl',
'DDIAZ_CL@VTR.NET',
'marceladuranduran@gmail.com',
'carolina.stubing19@gmail.com',
'jardinescampomanes@gmail.com',
'petit.nelly@gmail.com',
'EV@ELVIRAVALENZUELA.CL',
'gnicole.andrea@gmail.com',
'andreslunab@hotmail.com',
'cevicuna@gmail.com',
'alejandroperezpeters@gmail.com',
'mario.guiloff@gmail.com',
'ARRAUS.MJ@GMAIL.COM',
'claudio.ferrada@live.com',
'ING.FELIPE.GUERRERO@GMAIL.COM',
'valentina.abalo@gmail.com',
'eliette.herradura@yahoo.es',
'PHARTUNGM@GMAIL.COM',
'veronicagatica@gmail.com',
'promanr@gmail.com',
'karroninus@gmail.com',
'j.vicencio@colver.cl',
'aleschain@hotmail.com',
'gracielasn@hotmail.com',
'MARTINPERO2003@GMAIL.COM',
'marcos.valenzuela@gmail.com',
'alejgodoy@yahoo.es',
'pzuniga@vespucionorte.cl',
'silvanapavez.pena@gmail.com',
'educadora.karentorres@gmail.com',
'cecivgt@gmail.com',
'juaneduardo.pizarro@eqifax.cl',
'lbarreram@gmail.com',
'carlos-melo-s@hotmail.com',
'mchv.1980@gmail.com',
'pamelajeriapeperic@gmail.com',
'marielbeker@gmail.com',
'pfarfan@verbar.cl',
'MARICARMEN0409@GMAIL.COM',
'MALUCHICHA@GMAIL.COM',
'rjlfsimons@gmail.com',
'BLAMBERGARI@GMAIL.COM',
'ramonbenitezaranguiz@hotmail.com',
'lfwuth@hotmail.com',
'afuenzalida.palma@gmail.com',
'MPAZARAB@GMAIL.COM',
'aletetuppe@gmail.com',
'cristian.arcos@chilevision.cl',
'fcomarciel@live.com',
'mariajose_cote21@hotmail.com',
'grabriellajaraa@gmail.com',
'leonardokine16@gmail.com',
'ugonzalezc@gmail.com',
'lia_76@live.cl',
'sbellocchio@gmail.com',
'petersen.segsue@gmail.com',
'caravenaduran@gmail.com',
'caroleiva20@hotmail.com',
'salinasbustamante.camila@gmail.com',
'rwurgaft@gmail.com',
'paz.astudillo@gmail.com',
'franjomi.gas21@gmail.com',
'carolrabiech@gmail.com',
'xaltuzarra@gmail.com',
'tomarielag@gmail.com',
'ximarni@hotmail.com',
'mariola.saldarriaga@gmail.com',
'cataran@hotmail.com',
'anacona.carolina@gmail.com',
'vlarrondo@gmail.com',
'JCRQ77@GMAIL.COM',
'correo.cristian@gmail.com',
'isabelscheuch@gmail.com',
's.santibanez508@gmail.com',
'sebastian.hernandez.avendano@gmail.com',
'MAYERLIN_CARRUYO@HOTMAIL.COM',
'danielabelmart@gmaill.com',
'negal.rivero@gmail.com',
'carolina@consultorapanal.com',
'ravelis@gmail.com',
'MSERRAZURIZ@GMAIL.COM',
'jorgedp72@hotmail.com',
'dalibormilkovic@gmail.com',
'fdavila@banmedica.cl',
'hcalderovtr@gmail.com',
'jmbmd33@gmail.com',
'metulain@dicenciasonline.com',
'jaelalvo@gmail.com',
'gonzalo.aguilar.d@gmail.com',
'silvana.caroca@gmaIL.com',
'daniel.endi@gmail.com',
'jaime_rivera_md@yahoo.es',
'carlamnouel@hotmail.com',
'carocevallosbarrera@hotmail.com',
'danielruz.galvez@gmail.com',
'inunez_13@hotmail.com',
'mbenavente@arbolcolor.cl',
'alvarezlobofran@gmail.com',
'candypatino25@hotmail.com',
'claumeramunoz@gmail.com',
'ana.brandt@gmail.com',
'andyter@yahoo.com',
'olirav@aol.com',
'marchant.mariana@gmail.com',
'cgotelliw@gmail.com',
'dfoncea@gmail.com',
'paulacorreal@yahoo.es',
'defnny@gmail.com',
'ALAGOSVARELA@GMAIL.COM',
'carito7510@gmail.com',
'cpaz.peralta@gmail.com',
'cecilianbi@yahoo.com',
'francobasualto@gmail.com',
'edgalopez@gmail.com',
'imelnick@aol.com',
'raqel1703@gmail.com',
'vhutter@hofmann.cl',
'viviana.bugueno@gmail.com',
'tatacruci14@gmail.com',
'camila.jorquera.o@gmail.com',
'CECILIABEZ@HOTMAIL.COM',
'tamita2_87@hotmail.com',
'spavezl@gmail.com',
'papiruza2@gmail.com',
'camilavernal@gmail.com',
'josmig888@gmail.com',
'dacampos@puc.cl',
'maricelcm@gmail.com',
'lodasid@gmail.com',
'daguileram.qf@gmail.com',
'vespinosa@kikirikits.cl',
'nancy.pardo@live.cl',
'mjdurang@gmail.com',
'paduni@gmail.com',
'JOEGEYANKOVIC@GMAIL.COM',
'pablovn@gmail.com',
'tomaedo@gmail.com',
'caroguerracarrasco@gmail.com',
'eitan@fardo.cl',
'fco.jose.f@gmail.com',
'jpsanchezgarcia@gmail.com',
'alexrenevegaolivares@gmail.com',
'cata.poblete.ll@gmail.com',
'MPCASTILSTER@GMAIL.COM',
'fernanda.cabadillas@santander.cl',
'cosntazabarrosoj@gmail.com',
'stephaniechavarriatoro@gmail.com',
'coteblanco89@hotmail.com',
'eduardoj@me.com',
'javiera.fisher@gmail.com',
'pietrotauria17@gmail.com',
'aydembalajes@gmail.com',
'Neliaflores@hotmail.es',
'pazbarboza@hotmail.com',
'ka.saez@gmail.com',
'mjosevasquez@gmail.com',
'lidiamont@yahoo.cl',
'andreacarolina.mp@gmail.com',
'zacariasclaudia@gmail.com',
'danyespy2@gmail.com',
'camilacisternasz@gmail.com',
'cponcecaballero@gmail.com',
'pas7979@hotmail.com',
'dnavarro.toro@gmail.com',
'arturgarcia@outcklo.com',
'jvidall@dartel.cl',
'jcarcaval@hotmail.com',
'mjriquelme@gmail.com',
'yuyi@live.cl',
'IVETTE.VALDERRAMA.C@GMAIL.COM',
'aarayagu@uce.cl',
'MARIA.AUAD@MI.CL',
'MCASSISM@HOTMAIL.COM',
'hernandez.chr@gmail.com',
'teckaeltzerf@gmail.com',
'maopazo@gmail.com',
'fjdelpozo@gmail.com',
'luis_coa83@yahoo.com',
'rodrigosilva73@gmail.com',
'MARIPAULEK@HOTMAIL.COM',
'mtsilvav@gmail.com',
'margarita.alvares.l@gmail.com',
'trmatiasponce@gmail.com',
'claudiapoggio84@gmail.com',
'mabaud@gmail.com',
'alison.serrano@gmail.com',
'LIZZIEKABALAN@GMAIL.COM',
'aretuet@gmail.com',
'alfredo@skmedical.cl',
'mjcasals@gmail.com',
'ceciliatrigodaroni@gmail.cojm',
'christian.guerrag@gmail.com',
'rodrigo.carroza@gmail.com',
'manuel.reyes84@gmail.com',
'patybottai@gmail.com',
'DANIELAACEITUNO@HOTMAIL.COM',
'allvaro_0910@hotmail.com',
'monicagarciat@gmail.com',
'garansibiaf@me.com',
'gino.suppa@gmail.com',
'lorenavillarroelg@gmail.com',
'alberto.arayarojas@gmail.com',
'danielmoralesbrucher@gmail.com',
'caro.lasala@gmail.com',
'solherre@gmail.com',
'familiaviearevalo@gmail.com',
'fer.chica@gmaill.com',
'romaya1977@hotmail.com',
'diegozunigaacosta@gmail.com',
'mauro.bkp@gmail.com',
'daniza.faundez@gmail.com',
'daniel@invermaster.cl',
'ni.ibanez92@gmail.com',
'esteban.fuentes.morales@gmail.com',
'jbaraonau@gmail.com',
'julio@creastudio.cl',
'VERONICA.DAVANZO@GMAIL.COM',
'j.genacio.bravo@gmail.com',
'akikomc@gmail.com',
'mvelazquez07@gmail.com',
'YUVITZA.MUNOZ@GMAIL.COM',
'nicovicuna@gmail.com',
'fernanda.asp@gmail.com',
'ANAVILLABLANCA@HOTMAIL.COM',
'bsanchezblank@hotmal.com',
'felipefernandez79@gmail.com',
'soymontana@hotmail.com',
'ines.romero1@gmail.com',
'fram.marambio29@gmail.com',
'leonsacks84@gmail.com',
'pamevargas@hotmail.com'],
    junjulio: [
        'luis.cortes@gojump.cl',
        'benjamin.meneses.14@sansano.usm.cl',
        '19claudio87@gmail.com'
,'abitran@hebereo.cl'
,'adominguez@nialem.cl'
,'adricerra74@hotmail.com'
,'aguilar@hotmail.com'
,'agustina.avila.cremer@gmail.com'
,'ahumeres@gmail.com'
,'akurenga@gmail.com'
,'alain.quezada15@gmail.com'
,'ALAN@VITAMINAPRODCUCCIONES.CL'
,'alanfernandezgonzalez@gmail.com'
,'Ale.barra@hotmail.com'
,'alebatarce@gmail.com'
,'alechocar@hotmail.com'
,'alehuerta75@hotmail.com'
,'ALEJANDRA@HUMANFACTOR.CL'
,'alejandragollado.m@gmail.com'
,'alejandragonzalezmarmol@gmail.com'
,'alejandrogdelgado@gmail.com'
,'aletetuppe@gmail.com'
,'alexcockbaine@hotmail.com'
,'alfredoandrejs@hotmail.com'
,'alfredohernandez@yahoo.com'
,'alinaokita@yahoo.com.vr'
,'allelcamel@live.cl'
,'almendrag1@hotmail.com'
,'ALUCEMA@GMAIL.COM'
,'alvarezab.j@gmail.com'
,'alvarezlobofran@gmail.com'
,'alvarocerdasermeno@hotmail.com'
,'ammarinmartinez@hotmail.com'
,'ana.theodoro@cat.com'
,'anabel2307@hotmail.com'
,'anagonzalezllanos@gmail.com'
,'andrade.carolita@gmail.com'
,'andradenery@gmail.com'
,'andrea.cook.h@gmail.com'
,'andrea.llano@gmail.com'
,'andreacorvaz@yahoo.com'
,'andreagruber18@gmail.com'
,'andreamardones@gmail.com'
,'andreinapatricia97@hotmail.com'
,'andres.elgueta@gmail.com'
,'andres.marambio@icloud.com'
,'andres@citrica.cl'
,'angelagutierrez035@gmail.com'
,'angelica.vz@gmail.com'
,'angelicahmn@gmail.com'
,'angellarepetto@gmail.com'
,'anitapinilla@gmail.com'
,'anmedina.@hotmail.com'
,'antoniabbr2001@gmail.com'
,'antonio_mejia@hotmail.com'
,'anto_rojas@hotmail.com'
,'araya.castro.yeimi@gmail.com'
,'ariel.aguiler@gmail.com'
,'armijo.rodrigo@gmail.com'
,'aronchaareeonchi1@hotmail.com'
,'arotrel1966@yahoo.com'
,'artifix@gmail.com'
,'arvega@gmail.com'
,'asancheh@hotmail.com'
,'atatapiag2015@gmail.com'
,'avelsantiago1975@gmail.com'
,'avicuna79@gmail.com'
,'axelc1@hotmail.com'
,'axelrodriguez.sh@gmail.com'
,'AYBEN.CARDENAS@ACCENTURE.COM'
,'aylinnetamara@hotmail.com'
,'b.orellanalopez@gmal.com'
,'barbara.cabreracb@gmail.com'
,'BARBARABRICENOSOTO@GMAIL.COM'
,'barbarita_ortiz@hotmail.com'
,'barreau.cristian@gmail.com'
,'be.espinoza.r@gmail.com'
,'benjaagustin1986@gmail.com'
,'BERNADITA.VIAL@GMAIL.COM'
,'bertolet@gmail.com'
,'bpera77@GMAIL.COM'
,'bryan.spencer@ing.uchile.cl'
,'bsalinasc@gmail.com'
,'c.arayasanmartin@gmail.com'
,'c.consuegra@gmail.com'
,'c.labrin.v@gmail.com'
,'c.lisbooaromero@gmail.com'
,'c.romero.h@gmail.com'
,'caam74@gmail.com'
,'cabarzuac@gmail.com'
,'cadyale@gmail.com'
,'camila.jorquera.o@gmail.com'
,'camilabernal@gmail.com'
,'camilacisternasz@gmail.com'
,'caravenaduran@gmail.com'
,'carla.reloaded@gmail.com'
,'carlapintor@gmail.com'
,'carlos-melo-s@hotmail.com'
,'carlos.huentenao@gmail.com'
,'carlos.morasori@gmail.com'
,'carlos.trigo.m@gmail.com'
,'carlosescobars@yahoo.com'
,'carlosnarajo11@hotmail.com'
,'carlotafritsch@vtr.net'
,'carmen.berrios@gmail.com'
,'carmengloria.basualto@gmail.com'
,'carobascunan@yahoo.es'
,'CAROLA0872@GMAIL.COM'
,'carolabernales@gmail.com'
,'carolapazm@hootmail.com'
,'carolina.althausen@gmail.com'
,'carolina.stubing19@gmail.com'
,'carolinaagafonow@gmail.com'
,'carolinaespinizab@gmail.com'
,'carolinakhawam@gmail.com'
,'carolinapachecoocallo@hotmail.com'
,'carolinaurrutia74@hotmail.com'
,'carolina_fuente_alba@hotmail.com'
,'caroromero.rivas@gmail.com'
,'carostrube@gmail.com'
,'CAROVELASQUEZVIVAR@GMAIL.COM'
,'cata.perello@gmail.com'
,'catacortese@gmail.com'
,'catagomeztapia@gmail.com'
,'catagupi@hotmail.com'
,'catahornann@hotmail.com'
,'CATALANANA72@GMAIL.COM'
,'catalina.galleguillos@gmail.com'
,'catalina.ramos.b@gmail.com'
,'catalina.saezandaur@gmail.com'
,'cataran@hotmail.com'
,'ccanepa@gmail.com'
,'cc_mr@hotmail.com'
,'cdefeuris@dyb.cl'
,'cdoberti@gmail.com'
,'CECILIABEZ@HOTMAIL.COM'
,'cecilianbi@yahoo.com'
,'cecivgt@gmail.com'
,'celta007@yahoo.es'
,'cesarbuds@gmail.com'
,'cfelce@gmail.com'
,'cgaldamg05@gmail.com'
,'cguerraf@live.cl'
,'chabellapremo@hotmail.com'
,'chelautaro1@hotmail.com'
,'CHRIS.ARANEDA29@GMAIL.COM'
,'chris.f.j@hotmail.com'
,'cinavarrete@outlook.com'
,'cindy.piar@gmail.com'
,'cinthyavlg@gmail.com'
,'cintiamartinezr@hotmail.com'
,'cisternavidalluciano@gmail.com'
,'ckimberlee.22@gmail.com'
,'clau.albornosv@gmail.com'
,'claudia.alvareh@gmail.com'
,'CLAUDIA.RICHARST@YAHOO.CL'
,'claudiafa76@gmail.com'
,'claudio.aen@live.cl'
,'claudio.curkovic@gmail.com'
,'claudioreeve@gmail.com'
,'claumeramunoz@gmail.com'
,'cmarquerzba@gmail.com'
,'consuazuamorales@gmail.com'
,'CONSUELO.STY@GMAIL.COM'
,'consuelodiazdeco@gmail.com'
,'CONSUELOGMUNITA@GMAIL.COM'
,'contyconni@gmail.com'
,'CONYDAN@HOTMAIL.COM'
,'cortez.martina31@gmail.com'
,'costacristobal9@gmail.com'
,'cote.ortegabravo@gmail.com'
,'coterubio28@gmail.com'
,'cpaz.peralta@gmail.com'
,'cpitto@gmail.com'
,'cpmaturana@hotmail.com'
,'cramirezporras@gmail.com'
,'crisdelreal1999@gmail.com'
,'cristianapariciorojas@gmail.com'
,'cristianfmq@gmail.com'
,'cristiangiani@gmail.com'
,'cristobaljorquerae@gmail.com'
,'cristyhl@gmail.com'
,'csilvaduronea@gmail.com'
,'ctrino@tambochile.cl'
,'cvelascocisnero@gmail.com'
,'dabalosn@hotmail.com'
,'daisy.opazo@gmail.com'
,'DANIATORRESM@HOTMAIL.COM'
,'danibritoo@gmail.com'
,'daniel-2d@hotmail.com'
,'daniel.mollanos@hotmail.cl'
,'daniela.brunet@gmail.com'
,'daniela.chandia.g@gmail.com'
,'danieldelpozos@gmail.com'
,'danielmoralesbrucher@gmail.com'
,'danielmurillotoro@gmail.com'
,'danitza.vymazal@gmail.com'
,'davidcandia10@hotmail.com'
,'davismaster123@gmail.com'
,'delriomariateresa7@gmail.com'
,'denissehf@gmail.com'
,'denisverdugo@gmail.com'
,'devotto@gmail.com'
,'dfoncea@gmail.com'
,'dgarcialobos@gmail.com'
,'diaz.naty@gmail.com'
,'diazarasai@gmail.com'
,'diegohernandez.com@gmail.com'
,'diegopalvis@gmail.com'
,'diegovillagran.gonzalez@gmail.com'
,'dillanes@gmail.com'
,'dinagelin@hotmail.com'
,'DINAGELINGE@HOTMAIL.COM'
,'DRADUCCI@GMAIL.COM'
,'edmundo.flores@telefonica.com'
,'edu.riveros@gmail.com'
,'elguetabichet@gmail.com'
,'elisa.domingues2011@gmail.com'
,'emunyozb@gmail.com'
,'erlinjaquelinemateus@gmail.com'
,'estefania.saez@latam.com'
,'estela.b.pedrozo@gmail.com'
,'eveljara@gmail.com'
,'evergaragaray@gmail.com'
,'e_carts@hotmail.com'
,'fabianleongallegos@gmail.com'
,'fabiola.arismendi7@gmail.com'
,'facunataibo@gmail.com'
,'famigol@hotmail.com'
,'familiadiazulloa@gmail.com'
,'faruck8@yahoo.com'
,'Fcaquirozpinto@gmail.com'
,'fco.jose.f@gmail.com'
,'fco.monti@gmail.com'
,'fdelfierro@gmail.com'
,'felipe.brant@gmail.com'
,'felipe.meneses33@gmail.com'
,'felipechamorro@me.com'
,'felipefernandez79@gmail.com'
,'felipeff.1982@gmail.com'
,'ferafols@gmail.com'
,'fernanda.asp@gmail.com'
,'fernandaarrau@gmail.com'
,'fernandagfutierrezp@gmail.com'
,'fernando.espina@mediclownd.cl'
,'fg.so9fia@gmail.com'
,'fgarciaoldini@gmail.com'
,'fjs205@gmail.com'
,'fperezfrohlich@gmail.com'
,'fprieto25@gmail.com'
,'fram.marambio29@gmail.com'
,'francisca.nz@gmail.com'
,'francisca.zerega@mail.uvp.cl'
,'franciscafigueroa@gmail.com'
,'franciscamperez@gmail.com'
,'franciscapoblete@hotmail.com'
,'francisco.riquelme@prokart.cl'
,'franciscobassoqgmail@gmail.com'
,'frannudac@hotmail.com'
,'fran_g_f@yahoo.com'
,'fran_rpz@hotmail.com'
,'fsanhuezanunez@gmail.com'
,'fsolanich@idetex.cl'
,'ftirapegui@uc.cl'
,'gab.donoso@gmail.com'
,'gabiriosa2@gmail.com'
,'gabodepallens@gmail.com'
,'gajeria@gmail.com'
,'gcervellino@mosaico.cl'
,'gcontrer@gmail.com'
,'geraldinecaceres.s@gmail.com'
,'ggodoym@udd.cl'
,'gherrerabarrios@gmail.com'
,'gino.suppa@gmail.com'
,'glendatoloza@gmail.com'
,'GMUENA1987@GMAIL.COM'
,'gnicole.andrea@gmail.com'
,'gonpardo@yahoo.com'
,'gonzalocmr@hotmail.com'
,'gsolar@constructoralima.cl'
,'gtolate@uc.cl'
,'gustavo.marsal@gmail.com'
,'gustavodougherty@hotmail.com'
,'gvalenzuela11b@hotmail.com'
,'gvanzullia@gmail.com'
,'haichelis@gmail.com'
,'halperndaniel@gmail.com'
,'hectorortegal@hotmail.com'
,'henrrijcs@gmail.com'
,'hernan.palma@bci.cl'
,'hernandez.chr@gmail.com'
,'hersin@hotmail.com'
,'hmullerg@hotmail.com'
,'horacio.santana.urria@gmail.com'
,'hquijadas@gmail.com'
,'hugo.richter@gmail.com'
,'iansedaca@gmail.com'
,'icanales@lascondes.cl'
,'igleciasmasuela@gmail.com'
,'ignaciojaviermunoz@gmail.com'
,'illyta02@gmail.com'
,'inakashi@gmail.com'
,'inaki.villanueva@sura.cl'
,'info@brincabrinca.cl'
,'ING.FELIPE.GUERRERO@GMAIL.COM'
,'isabelgambi@gmail.com'
,'isaperezdearce@gmail.com'
,'isi.riutort@gmail.com'
,'ivandres.loyola@gmail.com'
,'ivanhoe181072@gmail.com'
,'ivanjarallanquiman53@gmail.com'
,'j.carlo2311@gmail.com'
,'jaa@123.cl'
,'jacqueline.avilez@gmail.com'
,'jaelalvo@gmail.com'
,'JAIME_RIVERA_MD@YAHOO.ES'
,'jamario@gmail.com'
,'jaque.carola@gmail.com'
,'jaurolo@gmail.com'
,'java.jav@gmail.com'
,'javi.henriquez24@gmail.com'
,'javibustose@gmail.com'
,'javicedo@gmail.com'
,'javier.albornoz.13@hotmail.com'
,'javier.hojas@gmail.com'
,'javier.padron@gmail.com'
,'javiera.fisher@gmail.com'
,'jbarrosu@gmail.com'
,'jbay@abacocominicaciones.cl'
,'jcarcaval@hotmail.com'
,'jcbustosrojas@gmail.com'
,'jeanette.avalos@gmail.com'
,'jechazu@polymerland.cl'
,'jeovanny.hermosilla@gmail.com'
,'jesanthauer@hotmail.com'
,'jesus_smr@hotmail.com'
,'JFITNSTERBUCH@YAHOO.COM'
,'JFLORES@ATOMO.CL'
,'jfurqueta@gmail.com'
,'jfvargas@entel.cl'
,'jhontrevol3107@gmail.com'
,'jiawad81@gmail.com'
,'jicardenas@cygabogados.cl'
,'JICORREG@GMAIL.COM'
,'jiescoba@gmail.com'
,'jignaciofdez@gmail.com'
,'jleneroi@gmail.com'
,'jmanriquez@altitudservocios.cl'
,'jmpascualr@gmail.com'
,'joaquin.antunezuribe@gmail.com'
,'joeltapia1@gmail.com'
,'jojaqueih@hotmail.com'
,'joprice.12@gmail.com'
,'jordandanielburgosfredes@gmail.com'
,'jorge.martinez.villarroel@gmail.com'
,'jorge.yanez.s@gmail.com'
,'jorge.zamora.aliaga@gmail.com'
,'jorgeurzua@yahoo.com'
,'jose@gmail.com'
,'josefina.gonzalez@gmail.com'
,'josefinagodoydidier@gmail.com'
,'josefinamore@gmail.com'
,'joseholgado@gmail.com'
,'joseluisp71@gmail.com'
,'josemanuel.ad@hotmail.com'
,'jpanne_oc@yahoo.es'
,'jphernandezcampos@gmail.com'
,'jplaut@contructo.cl'
,'jprestrada@gmail.com'
,'jrocha.alteregu@gmail.com'
,'jrodrigotroncoso@hotmail.com'
,'jrozas@gmail.com'
,'jschidt1970@outlock.cl'
,'JSPARADA@GMAIL.COM'
,'jthomasjt@gmail.com'
,'juan.antriao@saesa.cl'
,'juan.ignacio.soto@live.cl'
,'juancrisuper@gmail.com'
,'juanewallis@gmail.com'
,'juanlcd@hotmail.com'
,'juanpablorivera1809@gmail.com'
,'juanvlogs@gmail.com'
,'juaro93@hotmail.com'
,'juliegonzalez18d@hotmail.com'
,'julioguerrapostigo@gmail.com'
,'jvelascoe@udd.cl'
,'karen.kutz.bustos@gmail.com'
,'karim.vcabezas@gmail.com'
,'karinacontrabajo@gmail.com'
,'karinamorovic@gmail.com'
,'karla.benavides@gmail.com'
,'karlacarosilva@gmail.com'
,'kary.medina24@yahoo.es'
,'kate.sare.89@gmail.com'
,'kathrynsmga@gmail.com'
,'kathybn@hotmail.com'
,'katty.pestanitas@gmail.com'
,'kattycornejo@gmail.com'
,'kblisboa@gmail.com'
,'keiny_865@gmail.com'
,'kerlis@gmail.com'
,'kikagarces@hotmail.com'
,'KJROMO@UCE.CL'
,'klop_92@hotmail.com'
,'koke@live.cl'
,'kschwarzenberg@hotmail.com'
,'ksprasse@uc.cl'
,'lacereza.js@gmail.com'
,'landaeta.bendezu@gmail.com'
,'lauraviegas@yahoo.com'
,'lcaserzar@gmail.com'
,'lcatalina62@gmail.com'
,'leonardo_monte@yahoo.com'
,'leyterc@gmail.com'
,'lfwuth@hotmail.com'
,'lgalleguillos@goldenchile.cl'
,'lidia.gana@gmail.com'
,'lillitte_bebanives@hotmail.com'
,'LILYMOTTA@GMAIL.COM'
,'lorecos@gmail.com'
,'loretobnchi@hotmail.com'
,'loretofv@gmail.com'
,'loyan17@hotmail.com'
,'lozano.felipe@gmail.com'
,'lrbaezab@gmail.com'
,'lucasiniguez@gmail.com'
,'lucianorr@gmail.com'
,'lugati@gmail.com'
,'luzmalmg@gmail.com'
,'lydaprada@hotmail.com'
,'m.fernanda.uribe@gmail.com'
,'m.mojivilovic@hotmail.com'
,'m.ossa.zazzali@gmail.com'
,'m.pino.k@gmail.com'
,'mabel.rodriguezh@gmail.com'
,'mabobadi@uc.cl'
,'maca.ortiz@hotmnail.com'
,'maca.vergudo1989@gmail.com'
,'MACAMORAN@GMAIL.COM'
,'macarena.medel@gmail.com'
,'macarenacerdad@gmail.com'
,'macarenanavarrete@hotmail.com'
,'maibellysanchez@gmail.com'
,'majogalleguillos@gmail.com'
,'malejandrabadilla@gmail.com'
,'malejandraconchaOSSA@GMAIL.COM'
,'MAMENCGMS@YAHOO.COM'
,'manuel.joseortega@gmail.com'
,'maor@lwow.es'
,'maortega@gmail.com'
,'marcela.bonilla.oryan@gmail.com'
,'marcela.nieto.e@gmail.com'
,'marcelacervela@gmail.com'
,'marcela_sotolagos@gmail.com'
,'marcelo@mirax.cl'
,'marceloekdahl@hotmail.com'
,'marcelolinarest@gmail.com'
,'MAREMB_@HOTMAIL.COM'
,'marglory07@gmail.com'
,'maria.laura.mayer@gmail.com'
,'maria.paz.ahumada.mba@gmail.com'
,'mariajesusbm@gmail.com'
,'mariajose.godoysegura@gmail.com'
,'mariajosecarrascom@gmail.com'
,'mariajosecortines@gmail.com'
,'MARIALORETORIVAS@GMAIL.COM'
,'marialy08@hotmail.com'
,'mariana_gt@yahoo.com'
,'marianobertoto@hotmail.com'
,'maria_cambas_d@hotmail.com'
,'MARICARMEN0409@GMAIL.COM'
,'maricelalarenas@gmail.com'
,'maricris6075@gmail.com'
,'marigemisa@gamil.com'
,'mario.palma.1991@gmail.com'
,'mariolihernandezalvares@hotmail.com'
,'mariorosende@gmail.com'
,'MARISTEABOGADO@GMAIL.COM'
,'marisulrojas@gmail.com'
,'marta.herrera.s@vtr.net'
,'MARTINPERO2003@GMAIL.COM'
,'MARYCARMENMOLINA@HOTMAIL.COM'
,'marzankatherinereyes1@gmail.com'
,'MASIELALBORNOZ@GMAIL.COM'
,'mateodiaz@gmail.com'
,'matiasramo@gmail.com'
,'matiasuc@gmail.com'
,'maureinaclaudia69@gmail.com'
,'mauricio_stay@hotmail.com'
,'mauro.ramirez@enel.com'
,'maurofigueroa23@gmail.com'
,'maveried@gmail.com'
,'mbalthl@gmail.com'
,'mbisquett@gmail.com'
,'mbrito.instituciones@gmail.com'
,'mburmeis@yahoo.es'
,'MCARMONP@UC.CL'
,'mcerda@uc.cl'
,'mcotequezada@gmail.com'
,'mcuevas@komatsu.cl'
,'mdaniela.kine@gmail.com'
,'mdelrio@siembradulzura.cl'
,'mdiaz@andinadelsud.cl'
,'mdiazma@uc.cl'
,'MELANIA.PASSANTE@GMAIL.COM'
,'melina_couselo@hotmail.com'
,'mendozaybustos@gmail.com'
,'mesotovillazon@gmail.com'
,'metulain@dicenciasonline.com'
,'mfsaespina@gmail.com'
,'mfsantelicesq@gmail.com'
,'mfvalenz@yahoo.com'
,'mgarcia@sinekuanon.cl'
,'mgsaver@gmail.com'
,'mich.correa@yahoo.cl'
,'miguel.medalla@gmail.com'
,'miguelcarrascoy@gmail.com'
,'miguelmackay@gmail.com'
,'miguelramirezo@yahoo.com'
,'mih.aru@gmail.com'
,'mimontero@vtr.net'
,'misabeljc@gmail.com'
,'mitzi.jara@gmail.com'
,'mj.valenzuela@gmail.com'
,'mjcontrerasgardella@hotmail.com'
,'mjeldressalazar@gmail.com'
,'mjesusalessandri@gmail.com'
,'mjgonzalesa0710@gmail.com'
,'MJOSECASTELLON01@HOTMAIL.COM'
,'MMAGDALENAJIMENEZ@GMAIL.COM'
,'MMCALLEJA@ICLOUD.COM'
,'mmunozjordan@hootmail.com'
,'mmunozl@uce.cl'
,'molina.daniela@gmail.com'
,'molofeli@gmail.com'
,'monica.allen.beformes@gmail.com'
,'monicagarciat@gmail.com'
,'morenocabra@gmail.com'
,'MPAZARAB@GMAIL.COM'
,'mpertuz4@gmail.com'
,'mpiedadgana@gmai.com'
,'mplabrin@icloud.com'
,'mpradenas@gmail.com'
,'MSERRAZURIZ@GMAIL.COM'
,'mteredg@hotmail.com'
,'mtsilvav@gmail.com'
,'mvacostal@gmail.com'
,'nachaillanes@gmail.com'
,'nanciaravenaaguirre@gmail.com'
,'napauda@hotmail.com'
,'natalia.villabo@gmail.com'
,'nataliageguerrero.u@gmail.com'
,'nataliamorgadonav@gmail.com'
,'nataliavc@vtr.net'
,'nate.j.pugh@gmail.com'
,'natyrbs@hotmail.com'
,'naya.jael17@icloud.com'
,'nelsonnaviasosa@gmail.com'
,'ni.ibanez92@gmail.com'
,'nicolad.guerrero.m@gmail.com'
,'nicolas.ariadigital@gmail.com'
,'nicolas_bz@hotmail.com'
,'nicole.anabalon.m@hotmail.cl'
,'nicolebrender@gmail.com'
,'nisfran@gmail.com'
,'noliakingb@hotmail.com'
,'nspaslar@gmail.com'
,'ntlchavezrod@gmail.com'
,'n_sfeirs@hotmail.com'
,'Orianamurillok@gmail.com'
,'oscar.a.ad@gmail.com'
,'oscar.johansen@gmail.com'
,'oscarlara17@gmail.com'
,'ostoolaza.rodrigo@gmail.com'
,'otrosfranciscojabel@gmail.com'
,'ovalleca0420@gmail.com'
,'p.alcalde.e@gmail.com'
,'paaz.0912@gmail.com'
,'pablaridereli@gmail.com'
,'pablo.costela@gmail.com'
,'pablo.omar.ef@gmail.coom'
,'pablosraravia1007@gmail.com'
,'pablovaldesmedina@gmail.com'
,'pablovalenzuela@icloud.com'
,'pacc24@gmail.com'
,'pacsibmivm@gmail.com'
,'pacuadra@gmail.com'
,'pajimenez@gmail.com'
,'paltolim@gmail.com'
,'pame.sanhueza.c@gmail.com'
,'pamegoldschmidt@gmail.com'
,'pamelajeriapeperic@gmail.com'
,'pamelavarelafraser@gmail.com'
,'pamela_carmona1103@hotmail.com'
,'pam_sepulveda@yahoo.com'
,'pancho.alfaro@gmail.com'
,'paola.nunez.lugo@gmail.com'
,'paola.ramirez@talbot.cl'
,'patocoom@yahoo.com'
,'patricialdelier@gmail.com'
,'patricioarrietagodoy@gmail.com'
,'patriciovvu@gmail.com'
,'PATYCEA@YAHOO.COM'
,'pau.araya@gmail.com'
,'paulina.bustosbaesa@gmail.com'
,'paulinagarziacarcamo@gmail.com'
,'paulinapia.dintrans@gmail.com'
,'paumaturana@gmail.com'
,'pavez.diaz.fernando@gmail.com'
,'pavilanovich@gmail.com'
,'pbrecci@gmail.com'
,'pedro.rodriguez@teocisa.cl'
,'pedrochinj@gmail.com'
,'petit.nelly@gmail.com'
,'pf.tammorales@gmaIL.com'
,'pilopez@yapoo.com'
,'PJCONTRERAS@GMAIL.COM'
,'PLEON@CLC.CL'
,'pleonstehr@gmail.com'
,'polabarriga@gmail.com'
,'popaza@hotmail.com'
,'popsicats@icloud.com'
,'production@dtale.cl'
,'PROJASAMA6712@HOTMAIL.COM.AR'
,'promanr@gmail.com'
,'propiedades@avilesmartines.cl'
,'proyectaeventos21@gmail.com'
,'pserranojimenez@gmail.com'
,'pvaisman@gmail.com'
,'pvalenzuelarodriguez@gmail.com'
,'pvergarrp@uc.cl'
,'pzaratep@gmail.com'
,'pzuniga@vespucionorte.cl'
,'r.garcia@vid.cl'
,'r.vilchespino@gmail.com'
,'rafa_miranda@hotmail.com'
,'rafuentesz@gmail.com'
,'raulperry@gmail.com'
,'raultello1379@gmail.com'
,'rballimants@gmail.com'
,'rfrm1971@gmail.com'
,'rgiminez.flores@gmail.com'
,'ricardojgilg@gmail.com'
,'rivescarla1@gmail.com'
,'roberto.cordero@gmail.com'
,'robertomanubens@hotmail.com'
,'robertzambrano@yahoo.com'
,'rociocarolinab@gmail.com'
,'rociopenaperez@gmail.com'
,'ROCIOXCORREA@HOTMAIL.COM'
,'RODALLIENDE@GMAIL.COM'
,'rodiazsch@hotmail.com'
,'rodrigobandag@gami.com'
,'rodrigomoya.f@gmail.com'
,'ROJASPATRICIAANGELICA@GMAIL.COM'
,'romi@hotmail.com'
,'rosagalde@hotmail.com'
,'rosamariawatson3@hotmail.com'
,'rosirosalesm@hotmail.com'
,'ROSSANITA.NEGRETE@GMAIL.COM'
,'rubenbaldes@gmail.com'
,'ruber.lijeron@gmail.com'
,'rvelasquezf@gmail.com'
,'salvivictoriano@gmail.com'
,'SAMARILAOG@GMAIL.COM'
,'samuelventana@gmail.com'
,'sandi_cornejo@live.cl'
,'sandrasoms@gmail.com'
,'sbazaez@diacrom.cl'
,'sebarebeco@gmail.com'
,'sebastian.hernandez.avendano@gmail.com'
,'sesoto@uc.cl'
,'shuy_lyng@hotmail.com'
,'SILVANAGP@HOTMAIL.COM'
,'silviacalderon1@gmail.com'
,'skmr_23@yahoo.com'
,'sluengocatamar03@gmail.com'
,'SOFIASUAREZ06@YAHOO.COM'
,'soledad.trejo.rojas@gmail.com'
,'solherre@gmail.com'
,'solovaller@gmail.com'
,'sonlla77@gmail.com'
,'stephanie.milla@live.com'
,'syltorr@gmail.com'
,'tatacruci14@gmail.com'
,'teresadecastrog@gmail.com'
,'teresitasotomayor@gmail.com'
,'tilvelaura@gmail.com'
,'titipardo@gmail.com'
,'toli.jiminez@gmail.com'
,'tomaedo@gmail.com'
,'tomas.campana40@gmail.com'
,'totofico1902@gmail.com'
,'tpcontreraso@gmail.com'
,'trenzatex@gmail.com'
,'ugonzalezc@gmail.com'
,'uricohen@niusushi.cl'
,'uriel00@gmail.com'
,'usarich@outlook.com'
,'VALEGREENE@GMAIL.COM'
,'valen.vs.16@gmail.com'
,'valenzuela.macarena@gmail.com'
,'valezka.vera@gmail.com'
,'vanecadenas@gmail.com'
,'vanessa.hernandez.lugo@gmail.com'
,'vane_ohara@hotmail.com'
,'verini28@gmail.com'
,'veronica.medelt@gmail.com'
,'VERONOCA@PLAYTRAINING.CL'
,'vesarossi2012@gmail.com'
,'vicjiver@gmail.com'
,'victoria.barrera.ramos@gmail.com'
,'vimarlu@vtr.com'
,'vittozaffirie@gmail.com'
,'viturrieta@arqz-bin.com'
,'vivian.muchnik@gmail.com'
,'viviestayv@gmail.com'
,'vlarrondo@gmail.com'
,'voces@lives.cl'
,'vrivera_@hotmail.com'
,'willian.tin.17@gmail.com'
,'winyoguy@gmail.com'
,'xacuna@gmail.com'
,'XATOROR@GMAIL.COM'
,'xdelgado@colegiosscc.cl'
,'xfuentes2@gmail.com'
,'ximena.cuevas.a@gmail.com'
,'XIMENANTO@HOTMAIL.COM'
,'xt4mhz@gmail.com'
,'yani.fernandezarango@gmail.com'
,'ycayo@providencia.cl'
,'yee_yee_y@hotmail.com'
,'YERKA21@HOTMAIL.COM'
,'ymmiey@gmail.com'
,'yoyaherreral@gmail.com'
,'yrosemvlatt@gmail.com'
,'yuyi@live.cl'
,'zaidany.reyes@gmail.com'
,'zarelasante@hotmail.com',
'luis.cortes@gojump.cl',
'benjamin.meneses.14@sansano.usm.cl'

    ]
};

module.exports = lista;